#r "Microsoft.TeamFoundation.Build.Activities"
#r "Microsoft.TeamFoundation.Build.Client"
#r "Microsoft.TeamFoundation.Build.Common"
#r "Microsoft.TeamFoundation.Build.Workflow"
#r "Microsoft.TeamFoundation.Client"
#r "Microsoft.TeamFoundation.Common"
#r "Microsoft.TeamFoundation.Git.Client"
#r "Microsoft.TeamFoundation.SourceControl.WebApi"
#r "Microsoft.TeamFoundation.TestManagement.Client"
#r "Microsoft.TeamFoundation.TestManagement.Common"
#r "Microsoft.TeamFoundation.VersionControl.Client"
#r "Microsoft.TeamFoundation.VersionControl.Common"
#r "Microsoft.TeamFoundation.WorkItemTracking.Client"
#r "Microsoft.TeamFoundation.WorkItemTracking.Common"
#r "Microsoft.VisualStudio.Services.Common"
#r "Microsoft.VisualStudio.Services.WebApi"
#r "System.Activities"
#r "System.Net.Http"
#r "System.Xml"

#I __SOURCE_DIRECTORY__
//#r "../Tfs/bin/Debug/SourceLink.Tfs.dll" // in dev
#r "SourceLink.Tfs.dll"