// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("0.4.2")]
[assembly: AssemblyInformationalVersionAttribute("{\"buildVersion\":\"0.4.2-ci1411131841\",\"buildDate\":\"2014-11-13T18:41:59-08:00\"}")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.2";
    }
}
